#!/usr/bin/expect -f
#send_user "a [lrange $argv 0 0]\n"
#send_user "b [lrange $argv 1 1]\n"
#send_user "c [lrange $argv 2 2]\n"

set timeout 10
spawn [lrange $argv 0 0] [lrange $argv 1 1]
expect "LC-3b-SIM"
send "r [lrange $argv 2 2]\r"
expect {
	timeout {send_user "infiniteloop\r"; exit 1; }
	"LC-3b-SIM"
}
send "rd\r"
expect "LC-3b-SIM"

send "q\r"
interact
